version: "3"
services:
  web:
    image: nginx
    container_name: "${PROJECT_NAME}_nginx"
#    ports:
#      - "80:80"
    links:
     - php
     - database
    volumes:
      - ./docker/server.conf:/etc/nginx/nginx.conf:ro
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:cached
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
  php:
    build: ./docker/php-fpm-composer
    container_name: "${PROJECT_NAME}_php"
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html:cached

  database:
    image: postgres:alpine
    container_name: "${PROJECT_NAME}_db"
    environment:
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal
      - POSTGRES_DB=drupal
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  crond:
    image: wodby/drupal-php:7.3-dev-4.21.4
    container_name: "${PROJECT_NAME}_crond"
    environment:
      CRONTAB: "0 * * * * drush -r /var/www/html/web cron"
    command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
    volumes:
      - ./:/var/www/html:cached
  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
    #    - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  pgdata:
