version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    links:
     - php
     - database
    volumes:
      - ./docker/server.conf:/etc/nginx/nginx.conf:ro
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html

  php:
    build: ./docker/php-fpm-composer
    container_name: d9_php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html

  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal
      - POSTGRES_DB=drupal
    ports:
      - "5433:5432"
      volumes:
        - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
